name: Typescript CI

on:
    push:
        branches: [ '*' ]
    pull_request: 
        branches: [ '*' ]

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                npm ci

            - name: Run tests if test folder exists
              run: |
                if [ -d "tests" ]; then npm test; else echo "No tests"; fi
